version: "3"
services:
  nginx:
    build: ./nginx/
    restart: always
    container_name: atiq-nginx-container
    networks:
      - a1-net
    volumes:
      - /root/projects/data-uwsgi:/tmp/uwsgi/
      - /root/projects/data-db:/var/www/mysite/assets/
    ports:
      - "8888:80"
    depends_on: 
      - django

  django:
    build: .
    restart: always
    container_name: atiq-django-container
    command: >
      sh -c "python manage.py collectstatic --noinput 
      && python manage.py makemigrations
      && python manage.py migrate
      && uwsgi --ini mysite.uwsgi.ini"
    networks:
      - a1-net
    volumes:
      - /root/projects/data-uwsgi:/tmp/uwsgi/
      - /root/projects/data-web:/code/staticfiles/
      - /root/projects/data-web:/var/www/mysite/assets/
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    container_name: atiq-mysql-container
    networks:
      - a1-net
    ports:
      - 3306:3306
    volumes:
      - /root/projects/data-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=djangotodo
      - MYSQL_DATABASE=todo
      - MYSQL_ROOT_USER=root
      - MYSQL_PASSWORD=djangotodo

networks:
  a1-net:

